name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Grant write access to packages so we can push to GHCR
permissions:
  contents: read
  packages: write

jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          #    - name: Run flake8
          #      run: flake8 exporter.py

  test:
    name: Smoke Test Exporter
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install prometheus_client requests
          #      - name: Run exporter in background
          #        run: python exporter.py --once &
          #      - name: Wait for metrics
          #        run: |
          #          sleep 5
          #          curl --fail http://localhost:8000/metrics

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/proffalken/starling-exporter:latest

